/**
 * Preloaded example programs for VEIZAC simulator.
 * Each entry: { name, description, source }
 */

export const EXAMPLES = [
    {
        name: 'Add Two Numbers',
        description: 'Simplest program: compute C = A + B. Result at M(102).',
        source: [
            '; Compute C = A + B',
            '; A at 100, B at 101, result at 102',
            'ORG 0',
            'LOAD M(100)',
            'ADD M(101)',
            'STOR M(102)',
            'HALT',
            '',
            'ORG 100',
            'DATA 25',
            'DATA 17',
            'DATA 0'
        ].join('\n')
    },
    {
        name: 'Multiply Two Numbers',
        description: 'Demonstrates MUL and MQ register. Computes 6 × 9 = 54 at M(102).',
        source: [
            '; Multiply A * B using MUL instruction',
            '; A at 100, B at 101, result at 102',
            'ORG 0',
            'LOAD MQ,M(100)    ; MQ = A',
            'MUL M(101)        ; AC:MQ = MQ * B',
            'LOAD MQ           ; AC = lower 40 bits (the product)',
            'STOR M(102)       ; store result',
            'HALT',
            '',
            'ORG 100',
            'DATA 6',
            'DATA 9',
            'DATA 0'
        ].join('\n')
    },
    {
        name: 'Countdown Loop',
        description: 'Self-modifying code: counts from 10 to 0, stores each value at M(200+).',
        source: [
            '; Count down from 10 to 0',
            '; Stores each value in memory starting at address 200',
            '; Uses self-modifying code to increment the store address',
            'ORG 0',
            'LOAD M(50)           ; load counter (10)',
            'loop:',
            'STOR M(200)          ; store current value (address will be modified)',
            'SUB M(51)            ; subtract 1',
            'JUMP+ M(continue,0:19)',
            'HALT                 ; AC < 0 means done',
            'continue:',
            'STOR M(50)           ; save new counter',
            'LOAD M(3)            ; load the STOR instruction word (at addr 3)',
            'ADD M(52)            ; add 1 to address field',
            'STOR M(3,8:19)       ; write back modified address',
            'LOAD M(50)           ; reload counter',
            'JUMP M(loop,20:39)   ; loop back',
            'HALT',
            '',
            'ORG 50',
            'DATA 10              ; initial counter',
            'DATA 1               ; decrement value',
            'DATA 1048576         ; address increment (1 << 20)'
        ].join('\n')
    },
    {
        name: 'Sum Array',
        description: 'Sums 5 values using address modification. Result at M(110).',
        source: [
            '; Sum an array of 5 numbers at M(100)-M(104)',
            '; Uses self-modifying code to walk the array',
            '; Result stored at M(110)',
            'ORG 0',
            'LOAD M(50)           ; load 0 (running sum)',
            'STOR M(110)          ; clear result',
            'LOAD M(51)           ; load counter = 5',
            'STOR M(52)           ; save counter',
            'loop:',
            'LOAD M(110)          ; load running sum',
            'ADD M(100)           ; add array element (address will be modified)',
            'STOR M(110)          ; save updated sum',
            'LOAD M(52)           ; load counter',
            'SUB M(53)            ; counter - 1',
            'STOR M(52)           ; save counter',
            'SUB M(53)            ; test counter - 1',
            'JUMP+ M(inc,0:19)   ; if counter > 0, continue',
            'HALT                 ; done',
            'inc:',
            'LOAD M(5)            ; load ADD instruction word (addr 5)',
            'ADD M(54)            ; increment address field',
            'STOR M(5,8:19)       ; write back',
            'JUMP M(loop,0:19)    ; loop',
            '',
            'ORG 50',
            'DATA 0               ; zero',
            'DATA 5               ; array length',
            'DATA 0               ; counter storage',
            'DATA 1               ; constant 1',
            'DATA 1048576         ; address increment (1 << 20)',
            '',
            'ORG 100',
            'DATA 10',
            'DATA 20',
            'DATA 30',
            'DATA 40',
            'DATA 50'
        ].join('\n')
    },
    {
        name: 'Factorial (7! = 5040)',
        description: 'Computes 7! using loop and MUL. Result at M(102).',
        source: [
            '; Compute 7! = 5040',
            '; Result in M(102)',
            'ORG 0',
            'LOAD M(100)          ; load N into AC',
            'STOR M(101)          ; result = N (initial product)',
            'loop:',
            'LOAD M(100)          ; load counter',
            'SUB M(103)           ; counter - 1',
            'STOR M(100)          ; save decremented counter',
            'JUMP+ M(check,0:19) ; if counter-1 >= 0, check',
            'JUMP M(done,0:19)    ; counter went negative',
            'check:',
            'LOAD M(100)          ; load counter (N-k)',
            'SUB M(103)           ; test counter - 1',
            'JUMP+ M(mul,0:19)   ; if counter > 0, multiply',
            'JUMP M(done,0:19)    ; counter is 0, done',
            'mul:',
            'LOAD MQ,M(101)       ; MQ = result so far',
            'MUL M(100)           ; AC:MQ = result * counter',
            'LOAD MQ              ; AC = product (lower 40 bits)',
            'STOR M(101)          ; save updated result',
            'JUMP M(loop,0:19)    ; loop',
            'done:',
            'LOAD M(101)          ; load final result',
            'STOR M(102)          ; store to output',
            'HALT',
            '',
            'ORG 100',
            'DATA 7               ; N (decrementing counter)',
            'DATA 0               ; running product',
            'DATA 0               ; output',
            'DATA 1               ; constant 1'
        ].join('\n')
    },
    {
        name: 'Fibonacci Sequence',
        description: 'Computes first 10 Fibonacci numbers, stores at M(200)-M(209).',
        source: [
            '; Compute first 10 Fibonacci numbers',
            '; F(0)=0, F(1)=1, F(n)=F(n-1)+F(n-2)',
            '; Results stored at M(200) through M(209)',
            'ORG 0',
            'LOAD M(50)           ; load F(0) = 0',
            'STOR M(200)          ; store F(0)',
            'LOAD M(51)           ; load F(1) = 1',
            'STOR M(201)          ; store F(1)',
            'LOAD M(52)           ; counter = 8 (remaining iterations)',
            'STOR M(53)           ; save counter',
            'LOAD M(51)           ; prev1 = 1 (F(1))',
            'STOR M(54)           ; save prev1',
            'LOAD M(50)           ; prev2 = 0 (F(0))',
            'STOR M(55)           ; save prev2',
            'loop:',
            'LOAD M(54)           ; load prev1',
            'ADD M(55)            ; prev1 + prev2 = next',
            'STOR M(202)          ; store next (address will be modified)',
            'LOAD M(55)           ; old prev2',
            'STOR M(56)           ; temp = prev2',
            'LOAD M(54)           ; prev1',
            'STOR M(55)           ; prev2 = old prev1',
            'LOAD M(56)           ; temp (was prev2)',
            'ADD M(55)            ; new fib = prev1 + prev2',
            'STOR M(54)           ; prev1 = new fib',
            'LOAD M(53)           ; load counter',
            'SUB M(57)            ; counter - 1',
            'STOR M(53)           ; save counter',
            'SUB M(57)            ; test counter - 1',
            'JUMP+ M(next,0:19)  ; if > 0 continue',
            'HALT                 ; done',
            'next:',
            'LOAD M(8)            ; load STOR M(202) instruction (addr 8)',
            'ADD M(58)            ; increment address',
            'STOR M(8,8:19)       ; write back',
            'JUMP M(loop,0:19)    ; loop',
            '',
            'ORG 50',
            'DATA 0               ; F(0)',
            'DATA 1               ; F(1)',
            'DATA 8               ; iterations remaining',
            'DATA 0               ; counter storage',
            'DATA 0               ; prev1 storage',
            'DATA 0               ; prev2 storage',
            'DATA 0               ; temp storage',
            'DATA 1               ; constant 1',
            'DATA 1048576         ; address increment (1 << 20)'
        ].join('\n')
    }
];
