"""
VEIZAC Dashboard Generator
============================
Generates docs/dashboard.html from verify_sprint.py results.
The agent CANNOT edit dashboard.html directly — it must run this script.

Usage:
    python build_dashboard.py
"""

import json
import os
import sys
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).parent
STATE = ROOT / "state"
DOCS = ROOT / "docs"  # Dashboard stays in docs/

# Run verification first
sys.path.insert(0, str(ROOT))
from verify_sprint import verify_all, SPRINT_VERIFIERS, find_current_sprint


def load_budget():
    budget_path = STATE / "budget.json"
    if budget_path.exists():
        with open(budget_path, "r", encoding="utf-8-sig") as f:
            return json.load(f)
    return {"budget_limit": 1000000, "estimated_used": 0, "sprint_costs": {}}


def count_tests():
    """Count test files and estimate pass/fail from verification results."""
    tests_dir = ROOT / "tests"
    if not tests_dir.exists():
        return 0, 0
    test_files = list(tests_dir.glob("sprint-*.test.html"))
    return len(test_files), 0  # We can't run browser tests from Python


def generate_dashboard():
    results = verify_all()
    budget = load_budget()
    current_sprint, _ = find_current_sprint()
    test_files, _ = count_tests()
    
    total = len(results)
    done = sum(1 for r in results.values() if r["passed"])
    
    # Build progress bar
    filled = done
    empty = total - done
    bar_filled = "&#x2588;" * filled
    bar_empty = "&#x2591;" * empty
    
    # Build sprint rows
    sprint_rows = []
    for sprint_num in sorted(results.keys()):
        r = results[sprint_num]
        if r["passed"]:
            sprint_rows.append(
                f'        <div class="sprint" style="color:#0f0">&#x2705; Sprint {sprint_num} - {r["name"]} [DONE]</div>'
            )
        elif sprint_num == current_sprint:
            sprint_rows.append(
                f'        <div class="sprint" style="color:#ff0">&#x1F504; Sprint {sprint_num} - {r["name"]} [NEXT]</div>'
            )
        else:
            sprint_rows.append(
                f'        <div class="sprint todo">&#x2B1C; Sprint {sprint_num} - {r["name"]} [TODO]</div>'
            )
    
    # Build active sprint detail
    active_detail = ""
    if current_sprint is not None:
        checks = results[current_sprint]["checks"]
        detail_lines = [f'        <h2>Sprint {current_sprint} Details</h2>']
        for check in checks:
            icon = "&#x2705;" if check["pass"] else "&#x274C;"
            detail_lines.append(
                f'        <div class="feature">{icon} [{check["id"]}] {check["name"]}</div>'
            )
        active_detail = "\n".join(detail_lines)
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    used = budget.get("estimated_used", 0)
    limit = budget.get("budget_limit", 1000000)
    
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VEIZAC Build Dashboard</title>
    <style>
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{
            font-family: 'IBM Plex Mono', 'Courier New', monospace;
            background: #0d0d0d;
            color: #00ff88;
            padding: 2rem;
            line-height: 1.6;
        }}
        h1 {{ color: #00ff88; margin-bottom: 1rem; font-size: 1.5rem; }}
        h2 {{ color: #c9a227; margin: 1.5rem 0 0.5rem; font-size: 1.1rem; }}
        .section {{ margin-bottom: 1.5rem; padding: 1rem; border: 1px solid #333; }}
        .sprint {{ margin: 0.25rem 0; }}
        .todo {{ color: #666; }}
        .feature {{ margin: 0.2rem 0 0.2rem 1rem; color: #aaa; }}
        .bar {{ color: #c9a227; }}
        .dim {{ color: #555; }}
        .highlight {{ color: #fff; }}
        .warn {{ color: #ff4444; font-weight: bold; }}
    </style>
</head>
<body>
    <!-- THIS FILE IS AUTO-GENERATED by build_dashboard.py -->
    <!-- DO NOT EDIT MANUALLY — run: python build_dashboard.py -->
    <h1>&#x2550;&#x2550;&#x2550; VEIZAC Build Dashboard &#x2550;&#x2550;&#x2550;</h1>

    <div class="section">
        <h2>Sprint Status</h2>
{chr(10).join(sprint_rows)}
    </div>
    <div class="section">
        <h2>Overall Progress</h2>
        <div class="bar">{bar_filled}{bar_empty}  {done}/{total} sprints complete</div>
    </div>
    <div class="section">
{active_detail}
    </div>
    <div class="section">
        <h2>Tests</h2>
        <div class="highlight">{test_files} test file(s) found</div>
    </div>
    <div class="section">
        <h2>Budget</h2>
        <div class="highlight">~{used:,} / {limit:,} tokens</div>
    </div>
    <div class="section">
        <h2>Last Updated</h2>
        <div class="dim">{timestamp} (auto-generated by build_dashboard.py)</div>
    </div>
</body>
</html>
"""
    
    output_path = DOCS / "dashboard.html"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    
    print(f"Dashboard generated: {output_path}")
    print(f"Progress: {done}/{total} sprints verified")
    print(f"Budget: ~{used:,} / {limit:,} tokens")
    if current_sprint is not None:
        print(f"Next sprint: {current_sprint} — {results[current_sprint]['name']}")
    else:
        print("All sprints complete!")


if __name__ == "__main__":
    generate_dashboard()
